import 'package:hive_flutter/hive_flutter.dart';
import '../models/period.dart';
import '../models/cycle.dart';
import '../models/log_entry.dart';
import '../models/notification_settings.dart';
import '../models/sexual_activity_log.dart';

/// StorageService wraps all Hive database operations in one place.
///
/// Instead of opening Hive boxes everywhere in the app, we use this
/// single service. This makes it easy to:
///   - Find all database code in one file
///   - Swap Hive for another database later if needed
///   - Test the app by replacing this with a fake/mock
class StorageService {
  // Box names — think of a "box" like a table in a database.
  static const String _periodsBox = 'periods';
  static const String _cyclesBox = 'cycles';
  static const String _logEntriesBox = 'logEntries';
  static const String _settingsBox = 'settings';
  static const String _settingsKey = 'notificationSettings';
  static const String _sexualActivityBox = 'sexualActivity';
  static const String _prefsBox = 'prefs';
  static const String _themeModeKey = 'themeMode';

  /// Call this once when the app starts (in main.dart).
  /// It sets up Hive and registers our model types so Hive
  /// knows how to save/load them.
  static Future<void> init() async {
    await Hive.initFlutter();

    // Register adapters — these are generated by build_runner
    // and tell Hive how to convert our Dart objects to/from bytes.
    Hive.registerAdapter(PeriodAdapter());
    Hive.registerAdapter(CycleAdapter());
    Hive.registerAdapter(LogEntryAdapter());
    Hive.registerAdapter(LogTypeAdapter());
    Hive.registerAdapter(NotificationSettingsAdapter());
    Hive.registerAdapter(SexualActivityLogAdapter());
    Hive.registerAdapter(ProtectionTypeAdapter());

    // Open all boxes so they're ready to use immediately.
    await Hive.openBox<Period>(_periodsBox);
    await Hive.openBox<Cycle>(_cyclesBox);
    await Hive.openBox<LogEntry>(_logEntriesBox);
    await Hive.openBox<NotificationSettings>(_settingsBox);
    await Hive.openBox<SexualActivityLog>(_sexualActivityBox);
    await Hive.openBox(_prefsBox);
  }

  // ── Period operations ──────────────────────────────────────

  Box<Period> get _periods => Hive.box<Period>(_periodsBox);

  /// Save a new period to the database.
  Future<void> addPeriod(Period period) async {
    await _periods.add(period);
  }

  /// Get all saved periods, newest first.
  List<Period> getAllPeriods() {
    final periods = _periods.values.toList();
    periods.sort((a, b) => b.startDate.compareTo(a.startDate));
    return periods;
  }

  /// Update an existing period (e.g. when the user sets the end date).
  Future<void> updatePeriod(Period period) async {
    await period.save();
  }

  /// Delete a period.
  Future<void> deletePeriod(Period period) async {
    await period.delete();
  }

  // ── Cycle operations ───────────────────────────────────────

  Box<Cycle> get _cycles => Hive.box<Cycle>(_cyclesBox);

  Future<void> addCycle(Cycle cycle) async {
    await _cycles.add(cycle);
  }

  List<Cycle> getAllCycles() {
    final cycles = _cycles.values.toList();
    cycles.sort((a, b) => b.startDate.compareTo(a.startDate));
    return cycles;
  }

  Future<void> updateCycle(Cycle cycle) async {
    await cycle.save();
  }

  // ── Log entry operations ───────────────────────────────────

  Box<LogEntry> get _logEntries => Hive.box<LogEntry>(_logEntriesBox);

  Future<void> addLogEntry(LogEntry entry) async {
    await _logEntries.add(entry);
  }

  /// Get all log entries for a specific date.
  List<LogEntry> getLogsForDate(DateTime date) {
    return _logEntries.values.where((entry) {
      return entry.date.year == date.year &&
          entry.date.month == date.month &&
          entry.date.day == date.day;
    }).toList();
  }

  /// Get all log entries of a specific type (e.g. all symptom logs).
  List<LogEntry> getLogsByType(LogType type) {
    return _logEntries.values.where((entry) => entry.type == type).toList();
  }

  Future<void> deleteLogEntry(LogEntry entry) async {
    await entry.delete();
  }

  // ── Notification settings ──────────────────────────────────

  Box<NotificationSettings> get _settings =>
      Hive.box<NotificationSettings>(_settingsBox);

  /// Get the user's notification settings.
  /// Returns defaults if none have been saved yet.
  NotificationSettings getNotificationSettings() {
    return _settings.get(_settingsKey) ?? NotificationSettings();
  }

  /// Save the user's notification settings.
  Future<void> saveNotificationSettings(NotificationSettings settings) async {
    await _settings.put(_settingsKey, settings);
  }

  // ── Theme preference ──────────────────────────────────────

  Box get _prefs => Hive.box(_prefsBox);

  /// Get the saved theme mode. Returns 'system' if none saved.
  /// Possible values: 'system', 'light', 'dark'.
  String getThemeMode() {
    return _prefs.get(_themeModeKey, defaultValue: 'system') as String;
  }

  /// Save the theme mode preference.
  Future<void> saveThemeMode(String mode) async {
    await _prefs.put(_themeModeKey, mode);
  }

  // ── Sexual activity operations ────────────────────────────

  Box<SexualActivityLog> get _sexualActivity =>
      Hive.box<SexualActivityLog>(_sexualActivityBox);

  Future<void> addSexualActivityLog(SexualActivityLog log) async {
    await _sexualActivity.add(log);
  }

  /// Get the sexual activity log for a specific date, if any.
  SexualActivityLog? getSexualActivityForDate(DateTime date) {
    try {
      return _sexualActivity.values.firstWhere((log) =>
          log.date.year == date.year &&
          log.date.month == date.month &&
          log.date.day == date.day);
    } catch (_) {
      return null;
    }
  }

  /// Get all sexual activity logs for a given month.
  List<SexualActivityLog> getSexualActivityForMonth(int year, int month) {
    return _sexualActivity.values
        .where((log) => log.date.year == year && log.date.month == month)
        .toList()
      ..sort((a, b) => a.date.compareTo(b.date));
  }

  Future<void> updateSexualActivityLog(SexualActivityLog log) async {
    await log.save();
  }

  Future<void> deleteSexualActivityLog(SexualActivityLog log) async {
    await log.delete();
  }
}
